### ISSUE TITLE
SMACSS 可扩展模块化的 CSS 架构 0002

### ISSUE THREAD

**Issue by littlee** [littlee/CookaFrontend#14]
# SMACSS 可扩展模块化的 CSS 架构

https://smacss.com/book/type-base
# 基本规则

基本规则使用元素选择器、派生选择器或者后代选择器，以及任何伪类应用到元素。它不包含任何类或 ID 选择器。它定义着页面上所有情况下元素外观的默认样式。

``` css
body, form {
    margin: 0;
    padding: 0;
}

a {
    color: #039;
}

a:hover {
    color: 03f;
}
```

基本样式包括设置标题尺寸，默认链接样式，默认字体样式，和 body 背景颜色。没有必要在基本样式中使用 `!important`。

我极力推荐你声明一个 body 的背景颜色。一些用户可能会将不是白色的颜色定义他们自己的背景颜色。如果你有背景色是白色的工作期望，你的设计可能会受到破坏。更糟的是，你的字体颜色的选择会与用户的设置冲突，导致你的站点无法使用。
## CSS 重置

CSS 重置是用来剔除——或重置——默认外边距、内边距、和其他属性的基本样式的集合。它的目的是定义一个跨浏览器构建网站的一致基础。

许多重置框架存在过度的侵略性，引入的问题比它们解决的问题要多。从元素移除外边距和内边距只会让他们再次创建重复的影响，且增加了需要发送到客户端的代码量。

许多人发现重置样式是在站点开发中一个很好的工具。只需要认识到你所使用的框架的缺点并做出相应的对策。

开发自己的一套能一直在各个项目中使用的默认样式也是有好处的。
