### ISSUE TITLE
SMACSS 可扩展模块化的 CSS 架构 0003

### ISSUE THREAD

**Issue by littlee** [littlee/CookaFrontend#15]
# SMACSS 可扩展模块化的 CSS 架构

https://smacss.com/book/type-layout
# 布局规则

CSS，本质上是用来做页面元素的布局。然而，布局规定的主要和次要的组件存在了区别。次要的组件——例如以一个弹出框，或者一个登录表单，或者一个导航项——存在于主要组件的作用域中，例如头部或者尾部。我称次要的组件为模块，且我会在下一章节更详细地讨论。主要的组件被成为布局样式。

布局样式还可以基于重用的基础上，分离成主要样式和次要样式。主要布局样式例如头部或者尾部一般使用 ID 选择器进行样式设置，但是花点时间考虑下页面上所有组件通用的元素，使用 class 选择器会好一些。

``` css
#header, #article, #footer {
    width: 960px;
    margin: auto;
}

#article {
    border: solid #CCC;
    border-width: 1px 0 0;
}
```

某些站点会需要一个更通用的布局框架（例如，960.gs）。这些次要布局样式会使用类名，而不是 ID ，以便于样式可以在页面上使用多次。

一般来说，一个布局样式只有一个单一的选择器：一个单一的 ID 或者类名。然而，有些时候布局需要应对多种不用的因素。例如，基于用户的偏好，你可能会有不同的布局。这个布局偏好仍然会作为一个布局样式声明，并和其他布局样式结合使用。

``` css
#article {
    float: left;
}

#sidebar {
    float: right;
}

.l-flipped #article {
    float: right;
}

.l-flipped #sidebar {
    float: left;
}
```

在这个布局例子中，`.l-flipped` 类应用在一个更高层次的元素，例如 body 元素，且允许 article 和 sidebar 的内容进行交换，把 sidebar 从右边移动到左边，对于 article 反之亦然。

``` css
#article {
    width: 80%;
    float: left;
}

#sidebar {
    width: 20%;
    float: right;
}

.l-fixed #article {
    width: 600px;
}

.l-fixed #sidebar {
    width: 200px;
}
```

在上一个例子中，`.l-fixed` 类将布局的设计从流式改为固定。

还有一件在这个布局例子中需要注意的是我所使用的命名约定。使用 ID 选择器的声明进行了精确的命名，不带特定的命名空间。然而基于类的选择器，使用了 `l-` 前缀。这使得我们更容易认出这些样式的目的，并分离成模块或者状态。布局样式是唯一使用 ID 的主要分类，如果你选择使用它们。如果你希望给你的 ID 选择器添加命名空间，你可以这样做，但是这样不是很有必要。
### 使用 ID 选择器

简单明了，在 HTML 中使用 ID 属性是一件好事，且在某些情况下，绝对是必要的。例如，它们为 JavaScript 提供了高效的钩挂。然而对于 CSS，ID 选择器不是必要的，因为 ID 选择器和类选择器的性能差异几乎不存在，且会使得设置样式更加复杂，由于增加了明确性。
### 布局例子

理论和应用是两码事。让我们看一下一个实际的网站，考虑下什么是布局，什么是模块。

![](https://smacss.com/img/lyt-cnn0.png)

在观察 CNN 网站的时候，有许多发生在大量网站中的模式。例如，有一个头部，一个导航条，一个内容区域和一个尾部。

![](https://smacss.com/img/lyt-cnn1.png)

在编写本文的时候，这个网站紧紧跟随着这样的分解，并为这些主要的部分提供了 ID 属性。

``` css
#header { … }
#primarynav { … }
#maincontent { … }
```

``` html
<div id="header"></div>
<div id="primarynav"></div>
<div id="maincontent"></div>
```

这很直截了当，我认为你正在想，“真的吗？你就教我如何做这些事情？！” 让我们看一下页面上的另一部分。

![](https://smacss.com/img/lyt-cnn-ft0.png)

Taking a look at the Featured section, we see a grid of news items. CNN’s current markup is a container div with a series of child divs. I would have likely gone with an unordered list, so let’s do that instead.
看下推荐部分，我们看到了一个新闻项目的网格。CNN 目前的标记是一个 div 容器，包含着一系列子 div 。我可能会使用一个无序列表，让我们这样做吧。

``` html
<div>
<h2>Featured</h2>
<ul>
    <li><a href="…">…</a></li>
    <li><a href="…">…</a></li>
    …
</ul>
</div>
```

不考虑这个的 SMACSS 实现，我们可能会给外围的 div 添加 featured 的 ID，然后从那里开始设置样式。

``` css
div#featured ul { 
    margin: 0;
    padding: 0;
    list-style-type: none;
}

div#featured li {
    float: left;
    height: 100px;
    margin-left: 10px;
}
```

我们这样做带有以下假设：
1. 页面是只会有一个 featured 部分
2. 列表项向左浮动
3. 列表项有 100 像素的高度

这些可能是合理的假设。这是一个小网站可以脱离这样的架构的极好例子：它不太可能改变且它不会变得比已有的更加复杂。可能。更大的带有更高修改频率的网站会有更多重构组件的机会，且由于列表是 div 的一个直接子元素，孩子选择器可以使用。

让我们来看一下这可以如何重构来获得更好的灵活性。

从布局的角度看，我们关心的是每个元素与其他元素的联系。我们不必关系模块本身的设计，我们也不想担心这个布局所处的环境。

``` css
.l-grid {
    margin: 0;
    padding: 0;
    list-style-type: none;
}

.l-grid > li {
    display: inline-block;
    margin: 0 0 10px 10px; 

    /* IE7 hack to mimic inline-block on block elements */
    *display: inline;
    *zoom: 1;
}
```

我们这样做解决了什么问题以及带来了什么问题？（很少有解决方案解决 100% 的问题）
1. 网格布局可以应用到任何容器上来创建一个浮动分格的布局
2. 我们降低了 1 单位的应用性深度
3. 我们降低了选择器的明确性
4. 高度的需求移除了。行会增长到在行里最高的那个元素的高度。

在另一方面，我们使哪里更糟糕了？
1. 使用孩子选择器，我们把 IE 6 锁在门外
2. CSS 文件大小增加了，复杂性也增加了

文件大小的增加没有争论，但是它有名无实。现在我们有了这个可重用的模块，我们可以不用复制代码由始至终在站点上应用。复杂性的增加也是有名无实。我们确实必须解决过时的浏览器，然后丢一些可能让某些人眉头紧皱的 hack 。然而，选择器更加简单了，这允许我们在最小化明确性的影响的同事拓展这个布局。
