### ISSUE TITLE
SMACSS 可扩展模块化的 CSS 架构 0004

### ISSUE THREAD

**Issue by littlee** [littlee/CookaFrontend#16]
# SMACSS 可扩展模块化的 CSS 架构

https://smacss.com/book/type-module
# 模块规则

正如前面章节简短地提到过，模块是页面上更加离散的组件。它可以是你的导航条、你的轮播、
你对对话框、你的小部件等等。这是页面上的肉。模块位于布局组件的内部。模块有时也可以位于其他模块的内部。每个模块必须设计为独立的组件存在。这样做，页面会更加灵活。如果做的好，模块可以轻松地移动到布局中的不同部分，并不带任何破坏。

在为模块定义规则组合的时候，避免使用 ID 和元素选择器，仅仅使用类名。一个模块可能包含大量的元素，且我们期望使用派生选择器或孩子选择器来定位这些元素。

``` css
.module > h2 {
    padding: 5px;
}

.module span {
    padding: 5px;
}
```
## 避免元素选择器

如果元素选择选择器是可以预先知道的，将使用孩子或派生选择器与元素选择器一起使用。如果一个 span 会在预期情况下使用且每次在模块里都按照同样的方式设置样式，使用 `.module span` 是极好的。

``` html
<div class="fld">
    <span>Folder Name</span>
</div>
```

``` css
/* The Folder Module */
.fld > span {
    padding-left: 20px;
    background: url(icon.png);
}
```

问题是随着项目的复杂性的增加，你越可能需要拓展一个组件的功能，你就越受到在你的规则中使用一般元素的限制。

``` html
<div class="fld">
    <span>Folder Name</span> 
    <span>(32 items)</span>
</div>
```

现在我们处于困境。我们不想在我们的文件夹模块的两个元素都出现图标。这带领我们走到下一步：

只包含带有语义的选择器。一个 span 或 div 没有任何语义。一个 heading 就带有一些。一个定义在元素上的类名就带有许多语义。

``` html
<div class="fld">
    <span class="fld-name">Folder Name</span> 
    <span class="fld-items">(32 items)</span>
</div>
```

通过为元素添加类，我们增加了这些元素的语义，移除了在设置样式的时候的不明确性。

如果你确实想使用元素选择器，它必须带有一层类选择器。另外一种说法，你必须在这种情况下使用孩子选择器。非此即彼，你应该对问题中的元素不会与其他元素混淆非常自信。HTML 元素越有通用的语义（如 span 或 div），它越有可能在未来一段时间产生冲突。带有更强语义化的元素，如 heading，更有可能在容易中单独出现，你更有可能成功使用元素选择器。
## 新上下文

使用模块的方法也允许我们更好的理解上下文可能会在哪里改变。新的定位上下文的需要，例如，可能发生在布局层次或者模块根层次。
## 子类化模块

当我们在不同的部分有同样的模块的时候，第一个直觉是使用父元素来设置不同的模块样式。

``` css
.pod { 
    width: 100%; 
}
.pod input[type=text] { 
    width: 50%; 
}
#sidebar .pod input[type=text] { 
    width: 100%; 
}
```

这个方法的问题是，你会陷入明确性的大坑，需要添加更多的选择器来对抗明确性，或者快速回落到使用 `!important`。

扩展我们的 pod 例子，我们有两个不同宽度的输入框。在整个站点中，输入框有附带的 label ，因此它必须是一半的宽度。然而在侧栏中，这个控件太小了，所以我们将宽度增加到 100% 且把 label 放在顶部。看起来不错的样子。现在，我们需要往页面上添加新的组件。它使用了大多数与 `.pod` 相同的样式，所以我们重用了类名。然而，这个 pod 是特例，无论它位于站点的任何地方都有一个约束的宽度。这有点不同，但是它需要一个 180 像素的宽度。

``` css
.pod { 
    width: 100%; 
} 
.pod input[type=text] { 
    width: 50%; 
}
#sidebar .pod input[type=text] { 
    width: 100%; 
}

.pod-callout { 
    width: 200px; 
}
#sidebar .pod-callout input[type=text],
.pod-callout input[type=text] { 
    width: 180px; 
}
```

我们加倍了选择器让它可以覆盖 `#sidebar` 的明确性。

相反，我们应该做的是，意识到在侧栏里约束的布局是 pod 的一个子类，并根据需要设置样式。

``` css
.pod { 
    width: 100%; 
} 
.pod input[type=text] { 
    width: 50%; 
}
.pod-constrained input[type=text] { 
    width: 100%; 
}

.pod-callout { 
    width: 200px; 
}
.pod-callout input[type=text] { 
    width: 180px; 
}
```

子类化了模块，基本模块和子类模块的类名都应用到 HTML 元素上。

``` html
<div class="pod pod-constrained">...</div>
<div class="pod pod-callout">...</div>
```

尝试避免根据位置进行条件化的样式。如果你想为了在页面或站点的其他地方使用而改变模块的外观，对模块进行子类化。

``` css
.pod.pod-callout { }
```

``` html
<div class="pod pod-callout">...</div>
```

你可能会关系这个，取决加载的顺序。例如，在雅虎邮件，我们有来自不同地方的代码。我们有基本按钮样式，还有一系列特殊按钮。然而，点击添加通讯录带地址簿的时候，它加载了另一个产品的组件：地址簿。地址簿加载了它自己的基本按钮样式，从而覆盖了我们已有的子类按钮样式。

如果加载顺序是你项目中的一个因素，注意明确性问题。

虽然分配了 ID 的更明确的布局组件可以用来为模块提供特殊样式，但是子类化模块可以允许模块更容易地移动到页面上的其他部分，也避免了你增加不必要的明确性。
