### ISSUE TITLE
SMACSS 可扩展模块化的 CSS 架构 0006

### ISSUE THREAD

**Issue by littlee** [littlee/CookaFrontend#18]
# SMACSS 可扩展模块化的 CSS 架构

https://smacss.com/book/type-theme
# 主题规则

主题规则在项目中不是很经常使用，且因为这样，它们没有包含在核心类型里面。一些项目可能需要它们，正如我们在开发雅虎邮件的时候。
## 主题

很有可能不言而喻，但是一个主题定义了颜色和图片，给你的应用或站点提供外观和感觉。将主题分离成它自己的一个样式集合，允许这些样式很容易在切换主题时可以重新定义。

主题可以影响任何主要类型。它可以覆盖基本样式，比如默认链接颜色。它可以改变模块元素，例如铬黄色和边框。它可以在不同的安排下影响布局。它还可以改变状态的工作方式。

假设你有一个对话框模块，需要一个蓝色的边框，边框本身会在模块中进行初始化定义，然后主题定义了颜色。

``` css
/* in module-name.css */
.mod {
    border: 1px solid;
}

/* in theme.css */
.mod {
    border-color: blue;
}
```

主题可以有类名，清晰地指明，哪些样式是主题的一部分哪一些不是。拥有一个分离的主题文件已经足够了。

在雅虎邮件中，为了维护主题之间的一致性——我们有超过 50 ——我们为 CSS 使用 Mustache 模板，允许我们指定大量的颜色值，一个背景图片，然后为生产环境创建最终的 CSS 。
## 排版

最后也是最重要的，还有字体规则，与主题类似，很多时间你需要重新定义在整个基础中使用的字体，例如国际化。像中国或者韩国这样的地区有复杂的字符，在小字体上很难阅读。因此，我们为每个地区创建创建了分离的字体文件，重新定义组件的字体大小。

字体规则一般会影响基本、模块和状态样式。字体样式一般不会在布局层面上进行声明，因为布局趋向于定位和布置，不做格式上的改变，例如字体或颜色。

正如主题文件，可能没有必要定义真正的字体类（例如 f-large）。你的站点必须只有 3-6 中字体大小。如果你的项目有超过 6 中字体大小声明，你的用户可能会注意到且你让站点更难维护。
