### ISSUE TITLE
SMACSS 可扩展模块化的 CSS 架构 0007

### ISSUE THREAD

**Issue by littlee** [littlee/CookaFrontend#19]
# SMACSS 可扩展模块化的 CSS 架构

https://smacss.com/book/state

[TOC]
# 改变状态

你已经在你面前打开了一份 Photoshop 文档，你需要将他们变成神奇的 HTML 和 CSS（也许再额外丢一些 JavaScript 进去）。

直接将作品映射到代码上看起来直截了当。然而，页面上的各个组件需要变成成不同的状态。默认状态下应该出现什么，改变状态时又会怎样。
## 什么是状态改变？

状态改变代表着三种方式之一：
1. 类名
2. 伪类
3. 媒体查询

一个 **类名** 的改变伴随着 JavaScript。通过某些交互，无论是鼠标悬停，键盘敲击，或者触发了其他事件。元素应用到一个新的类，然后改变了视觉外观。

一个 **伪类** 改变经过了任意数量的伪类，存在很多种。在这些情况下，我们不再需要依赖 JavaScript 来描述状态的改变。伪类依然存在这样的限制，我们只能改变应用了伪类的后代或者同辈元素的样式。如果不行，我们还是用回 JavaScript。

最后，**媒体查询** 描述在定义下的规则的样式，例如不同视口尺寸。

通过一个基于模块的系统，考虑基于状态设计，应用到每个模块是重要的。但你主动问你自己“什么是默认状态”的时候，你会发现你自己主动地思考如何循序渐进。它也会使你接近目标有点不同。
## 通过类名改变

在很大程度上，类名改变是直接的。它们应用到元素上，呈现一个不同的状态。例如，用户点击一个图标来显示或隐藏页面上的元素。

``` js
$('.btn-close').click(function () {
    $(this).parent('.dialog').addClass('is-hidden');
});
```

这个 jQuery 例子添加一个点击事件到每一个带有 `btn-close` 类名的元素上。当用户点击按钮的时候，它带着时间源，向上遍历 DOM 树，找到带有 `dialog` 类名的祖先元素。然后应用 `is-hidden` 的状态类。

其他时候，状态改变有很大的影响。

一个常见的用户界面设计模式是，按钮点击的时候，显示菜单。在这个情况下，按钮转变成一个按住的状态，菜单转变成一个可见的状态。我们有什么选择来处理这个变化？这很大取决于你的 HTML 结构。例如，在雅虎，菜单在请求的时候被载入，因此，插入到 DOM 的顶部。我们使用一个命名约定将这两个钩挂起来。

``` html
<div id="content">
   <div class="toolbar">
      <button id="btn-new" class="btn" data-action="menu">New</button>
   </div>
</div>
<div id="menu-new" class="menu">
   <ul> ... </ul>
</div>
```

data-action 绑定了 JavaScript 的点击调用，“嘿，你想要加载一个菜单。” 它会提取按钮的 ID 并找到匹配的菜单。这是一份可能的 jQuery 代码：

``` js
// bind a click handler to the button
$('#btn-new').click(function(){
    // wrap the clicked button in jQuery
    var el = $(this); 

    // change the state of the button
    el.addClass('is-pressed');

    // find the menu by stripping btn- and
    // adding it to menu selector
    $('#menu-' + el.id.substr(4)).removeClass('is-hidden');
});
```

在这个演示中，通过 JavaScript 改变了单一元素的状态，在两个不同地方的两个不同元素。

但是如果菜单就在按钮的下方呢？

``` html
<div id="content">
   <div class="toolbar">
      <button id="btn-new" class="btn" data-action="menu">New</button>
      <div id="menu-new" class="menu">
          <ul> ... </ul>
      </div>
   </div>
</div>
```

上面的代码同样可以工作，且可以肯定能保持原样。然而，我们有其他选择。你的第一直觉可能是添加一个类到父元素，然后从那里考试设置按钮和菜单的样式。

``` html
<div id="content">
   <div class="toolbar is-active">
      <button id="btn-new" class="btn" data-action="menu">New</button>
      <div id="menu-new" class="menu">
          <ul> ... </ul>
      </div>
   </div>
</div>
```

``` css
.is-active .btn { color: #000; }
.is-active .menu { display: block; }
```

这个做法的问题在于，HTML 结构现在绑在一起。必须有一个容器。菜单和按钮必须存在于容器里面。我们希望，我们不需要工具栏有更多的按钮！

另外一个做法是应用 `active` 类到按钮上，使用同辈选择器来激活菜单。

``` html
<div id="content">
   <div class="toolbar">
      <button id="btn-new" class="btn is-active" data-action="menu">New</button>
      <div id="menu-new" class="menu">
          <ul> ... </ul>
      </div>
   </div>
</div>
```

``` css
.btn.is-active { color: #000; }
.btn.is-active + .menu { display: block; }
```

我更喜欢这个做法，相比较于应用一个状态类到父元素，因为状态更准确地结合它所在的组件。它依然存在依赖，菜单的 HTML 需要紧挨着按钮的 HTML：一个必须紧跟着另一个。如果你能在你的项目中建立一致性，那么这是一个对你来说可行的方案。
### 为什么父元素和同辈元素的状态是存在问题的

这个做法会比仅仅应用状态到每个模块更操蛋的原因是，无法弄清这些规则应该往哪放。菜单就不仅仅是菜单了。它是一个按钮菜单。如果你需要修改这个模块的激活状态，你会在按钮 CSS 那里发现这些样式还是在菜单 CSS 那里？

总的来说，应用状态到每个按钮上是一个更好的做法。你会创建模块间更好的分离，使你的站点更好地测试，开发，扩展。
### 使用属性选择器处理状态的改变

取决于你的浏览器支持，你也可以利用属性选择器来处理状态改变。这很有用，对于：
- 从布局和模块类中隔离状态
- 允许更容易地进行多个状态转换

让我们看一下一个存在多种状态的按钮的例子，例如默认，按住，禁用。

你可能会选择使用子模块命名约定。

``` css
.btn { color: #333; } 
.btn-pressed { color: #000; } 
.btn-disabled { opacity: .5; pointer-events: none; }
```

如果一个按钮需要转换状态，那么使用状态命名会更说的通。

``` css
.btn { color: #333; } 
.is-pressed { color: #000; } 
.is-disabled { opacity: .5; pointer-events: none; }
```

我喜欢这两个例子的比较，因为它强调了 SMACSS 经常是关于清晰度和命名约定。在同一个项目看到这个两个例子中的一个我都很高兴。现在让我们看一下另一个方法：属性选择器。

``` css
.btn[data-state=default] { color: #333; } 
.btn[data-state=pressed] { color: #000; } 
.btn[data-state=disabled] { opacity: .5; pointer-events: none; }
```

``` html
<button class="btn" data-state="disabled">Disabled</button>
```

属性 `data-` 前缀是 HTML5 规范中的一部分，允许你自定义属性名，然后存放在 data 命名空间里面，以便于不与未来的 HTML 属性规范产生冲突。改变一个按钮的状态不需要移除类或者增加类。只需要改变一个属性的值。

``` js
// bind a click handler to each button
$(".btn").bind("click", function(){
    // change the state to pressed
    $(this).attr('data-state', 'pressed');
});
```

不可否认，使用像 jQuery 这样的 JavaScript 库，为状态管理操作类是不复杂的。jQuery 有像 `hasClass`，`addClass`，和 `toggleClass` 的方法，使得操作类名真的很简单。

可以说，你有很多表示状态的方法的选择。
### 基于类状态改变的 CSS 动画

动画是一只有趣的野兽，有些人争论说，它定义在它原本不该定义的层次上的行为。CSS 终究是用来设置样式的。JavaScript 才是用来设置行为的。

这里的区别在于，要理解 CSS 定义一个可视状态。我们可以使用 JavaScript 来切换页面上元素的状态，但是，JavaScript 不应该用来描述状态。就是说，它不能用来添加内联的样式。

历史原因，我们已经使用过 JavaScript 来创建动画，因为这是我们唯一能做的。

当我们从这些条例中考虑这些事情，它可以帮助我们塑造如何实现不同情况的做法。例如，一个消息出现在页面上很短的时间，然后消失，是不常见的。

``` js
function showMessage (s) {
    var el = document.getElementById('message');
    el.innerHTML = s;

    /* set state */
    el.className = 'is-visible'; 
    setTimeout(function(){
        /* set state back */
        el.className = 'is-hidden';
    }, 3000);
}
```

消息的状态从 hidden 转换到 visible 然后又回到 hidden。JavaScript 处理这个状态的改变，然后 CSS 可以用于在这些状态间的动画，使用 transition 或者 animation

``` css
@keyframes fade {
    0% { opacity:0; display:block; }
  100% { opacity:1; display:block; }
}

.is-visible {
    display: block;
    animation: fade 2s;
}

.is-hidden {
    display: none;
    animation: fade 2s reverse;
}
```

我承认，最后一个例子不会真正工作。很不幸，现有的动画规范和浏览器实现不允许我们在动画中指明非动画属性。谢天谢地，规范依然在修改，最终应该会添加这个，浏览器也紧跟着实现。在此期间，我们需要做一些像下面这样的事情。

``` css
@-webkit-keyframes fade {
    0% { opacity:0;  }
  100% { opacity:1; display:block; }
}

.is-visible {
    opacity: 1;
    animation: fade 2s;
}

.is-hidden {
    opacity: 0;
    animation: fade 2s reverse;
}

.is-removed {
    display: none;
}
```

``` js
/* and then our javascript */
function showMessage (s) {
    var el = document.getElementById('message');
    el.innerHTML = s;

    /* set state */
    el.className = 'is-visible'; 
    setTimeout(function(){
        /* set state back */
        el.className = 'is-hidden';
        setTimeout(function(){
            el.className = 'is-removed';
        }, 2000);
    }, 3000);
}
```

在这种情况下，我把它改成了，仍然进行动画，但是使用 JavaScript 在动画完成后从文档流中移除这个元素。

使用这个方法，我们维护着样式（或者说状态）和行为的分离。
## 通过伪类改变

正如我们已经看过的，我们可以使用类和属性来处理模块上的状态定义。然而，CSS 提供了许多能帮助我们管理状态和状态改变的伪类。

从 CSS 2.1 开始，三个最有用的伪类，是响应用户交互的几个动态类，`:hover`, `:focus`, 和 `:active`。CSS 3 添加了一些新的伪类，大多数是基于 HTML 结构的样式（例如 `:nth-child` 或者 `:last-child` ）。在 CSS 3 中有一些是 UI 伪类，可以与表单交互进行响应，相当容易上手。

模块的默认状态一般是不带有伪类进行定义。伪类定义成模块的需要状态。

``` css
.btn {
    background-color: #333; /* gray */
}

.btn:hover {
    background-color: #336; /* blueish */
}

.btn:focus {
    /* blueish focus ring */
    box-shadow: 0 0 3px rgba(48,48,96,.3); 
}
```

因为模块是子类化的，可能会潜在地变得复杂，所以你可能也需要为子模块设计伪类状态。

``` css
.btn {
    background-color: #333; /* gray */
}

.btn:hover {
    background-color: #336; /* blueish */
}

.btn:focus {
    /* blueish focus ring */
    box-shadow: 0 0 3px rgba(48,48,96,.3); 
}

/* a default button state is the default choice from a
 * selection of buttons 
 */
.btn-default {
    background-color: #DEDB12; /* yellowish */
}

.btn-default:hover {
    background-color: #B8B50B; /* darker yellow */
}

/* no need to define a different focus state */
```

在上一个代码例子中，我们必要地创建了一个模块的 5 个不同变种：一个主模块，一个子模块，然后是伪类状态。它会变得更复杂，当我们介入基于类状态在每个选择器的开头的时候。

``` css
.btn { ... }
.btn:hover { ... }
.btn:focus { ... }

.btn-default { ... }
.btn-default:hover { ... }

.btn.is-pressed { ... }
.btn.is-pressed:hover { ... }

.btn-default.is-pressed { ... }
.btn-default.is-pressed:hover { ...; }
```

谢天谢地，你的界面中只有少数模块需要这一堆状态管理。然而，样式的恰当组织，可以确保你的项目更容易维护。
## 通过媒体查询改变状态

虽然通过类和伪类进行状态改变是常有的事，媒体查询快速成为了另一个管理状态改变的方法，一个传统上只能通过 JavaScript 的实现的方法。适应设计和响应式设计使用媒体查询来相迎不同的规则。打印样式表是允许我们定义在打印的时候页面上的元素的外观的一种媒体查询。

媒体查询可以定义在一个分离的样式表，使用 link 元素的 media 属性 ，或者定义在 @media 块里面。

``` html
<link href="main.css" rel="stylesheet">
<link href="print.css" rel="stylesheet" media="print">
```

``` css
/* inside main.css */
@media screen and (max-width: 400px) {
    #content { float: none; }
}
```

大多数媒体查询的例子定义了一个断点，然后把所有属于断点的样式丢进去。

在 SMACSS 中，我们的目的是保持样式属于特定的模块，跟随在模块样式的后面。这意味着，不仅仅只有一个断点，无论是在主要的 CSS 文件或者一个分离的媒体查询样式表，而是把媒体查询写在模块状态的周围。

``` css
/* default state for nav items */
.nav > li {
   float: left;
}

/* alternate state for nav items on small screens */
@media screen and (max-width: 400px) {
    .nav > li { float: none; }
}

... elsewhere for layout ...

/* default layout */ 
.content { 
    float: left;
    width: 75%;
}

.sidebar {
    float: right;
    width: 25%;
}

/* alternate state for layout on small screens */
@media screen and (max-width: 400px) {
    .content, 
    .sidebar { 
        float: none;
        width: auto; 
    }
}
```

是的，这的确意味着媒体查询声明可能声明多次，但是这样做也允许了把模块的所有信息整合在一起。记住，把模块信息整合在一起，允许模块的独立测试，允许像模块化模板之类的资源和 CSS 在初始化页面被加载之后才进行加载。
## 一切都是为了状态

This chapter reviewed the three types of state change: class, pseudo-class, and media query. Thinking about your interface not only modularly but as a representation of those modules in various states will make it easier to separate styles appropriately and build sites that are easier to maintain.

这一章节复习了三种类型的状态改变：累、伪类、媒体查询。考虑到你的界面不止是模块化的，而且作为这些模块在不同状态的表现，会使得更容易恰当分离样式，构建更容易维护的站点。
